language: python
python:
  "3.8"
install:
  pip install .
  pip install pytest
script: pytest
deploy:
  on:
    all_branches: true
    tags: true
  provider: pypi
  username: __token__
  password: $PYPI_TOKEN
