language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install pytest
script: pytest
deploy:
  - provider: pypi
  - username: __token__
  - password: 
    - secure: TEST_PYPI_API
  - on:
    - tags: true
  - server: https://test.pypi.org/index
  
